version: '3.8'
services:
  redis:
    image: redis:7
    ports:
      - 6379:6379

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: fileengine
      POSTGRES_USER: fileengine
      POSTGRES_PASSWORD: fileengine
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  file-engine:
    build:
      context: .
      dockerfile: build/docker/server.Dockerfile
    ports:
      - 8080:8080
      - 50051:50051
    environment:
      REDIS_ADDR: redis:6379
      POSTGRES_DSN: postgres://fileengine:fileengine@postgres:5432/fileengine?sslmode=disable
      FILE_BASE_ROOT: /mnt/files
      STORAGE_BACKEND: local
      STORAGE_BACKEND: local
    volumes:
      - ./data:/mnt/files
    depends_on:
      - redis
      - postgres

  worker:
    build:
      context: .
      dockerfile: build/docker/worker.Dockerfile
    environment:
      REDIS_ADDR: redis:6379
      POSTGRES_DSN: postgres://fileengine:fileengine@postgres:5432/fileengine?sslmode=disable
      FILE_BASE_ROOT: /mnt/files
      STORAGE_BACKEND: local
    volumes:
      - ./data:/mnt/files
    depends_on:
      - redis
      - postgres
      - file-engine

volumes:
  pgdata:
